"""Configured isolation, zero-call planning and reusable paid translation results."""

import json
import os
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

from prompt_translation import config, translate, validation


@pytest.fixture
def profile(tmp_path, monkeypatch):
    root = tmp_path / "repository"
    source = root / "sources/prompts"
    source.mkdir(parents=True)
    path = tmp_path / "translation.json"
    data = {
        "schema": "prompt-translation/v1",
        "repository_root": str(root),
        "source_directory": "sources/prompts",
        "output_directory": "learning/pairs",
        "cheatsheet_path": "learning/cheatsheet.md",
        "models": {"translate": "synthetic-translator", "classify": "synthetic-classifier"},
        "api": {
            "base_url": "https://api.example.invalid/messages",
            "credential": {"environment": "SYNTHETIC_TRANSLATION_KEY", "kind": "selected"},
            "required": True,
        },
        "prompts": {
            "translate": "Synthetic configured translator.",
            "classify": "Synthetic configured classifier.",
            "cheatsheet": "Synthetic configured cheatsheet.",
        },
    }
    path.write_text(json.dumps(data))
    monkeypatch.setenv("SYNTHETIC_TRANSLATION_KEY", "synthetic-selected-key")
    monkeypatch.setattr(translate.time, "sleep", lambda *a: None)
    return path, data, root


def save(profile):
    profile[0].write_text(json.dumps(profile[1]))


def source(profile, name="2026-01-01_session.md", prompts=None):
    prompts = prompts or [
        (
            "2026-01-01 01:00:00Z",
            "这是一个用于验证完整翻译与增量复用行为的中文提示，其中包含完整的理由与计划。",
        )
    ]
    path = profile[2] / "sources/prompts" / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n\n".join(f"### {timestamp}\n\n{body}" for timestamp, body in prompts))
    return path


def run(profile, *args):
    return translate.main(["--config", str(profile[0]), *args])


class FakeMessages:
    def __init__(self, replies):
        self.replies = iter(replies)
        self.calls = []

    def create(self, **request):
        self.calls.append(request)
        return SimpleNamespace(content=[SimpleNamespace(text=next(self.replies))])


def fake_client(monkeypatch, replies):
    client = SimpleNamespace(messages=FakeMessages(replies))
    monkeypatch.setattr(translate, "make_client", lambda *a: (client, "synthetic"))
    return client


def validate_file(profile, filename):
    validation.configure(config.load(profile[0]))
    return validation.validate(profile[2] / "learning/pairs" / filename)


def test_config_preserves_prompt_bytes_revision_and_timestamp(profile, monkeypatch):
    source(profile)
    profile[1]["pipeline_revision"] = 2
    profile[1]["prompts"]["translate"] = "  Exact caller text.\nWith a final newline.\n"
    profile[1]["generated_marker"] = "<!-- Generated by a-caller-command."
    save(profile)
    client = fake_client(monkeypatch, ['["Translated result."]'])
    assert run(profile, "--date", "2026-01-01", "--no-classify") == 0
    request = client.messages.calls[0]
    assert request["system"][0]["text"] == profile[1]["prompts"]["translate"]
    assert request["system"][0]["cache_control"] == {"type": "ephemeral"}
    output = profile[2] / "learning/pairs/2026-01-01.md"
    assert "2026-01-01 01:00:00Z" in output.read_text()
    assert "pipeline_revision: 2" in output.read_text()
    assert profile[1]["generated_marker"] in output.read_text()
    assert validate_file(profile, "2026-01-01.md") == []


def test_committed_day_reuses_unchanged_translations_after_cache_loss_and_move(
    profile, monkeypatch
):
    original = source(profile)
    fake_client(monkeypatch, ['["Existing translation."]'])
    assert run(profile, "--date", "2026-01-01", "--no-classify") == 0
    original_text = original.read_text()
    original.unlink()
    moved = profile[2] / "sources/prompts/2026-01/2026-01-02_session.md"
    moved.parent.mkdir()
    moved.write_text(
        original_text
        + "\n\n### 2026-01-01 02:00:00Z\n\n这是新到达的第二个中文提示，用于验证旧记录可以继续复用而无需重新支付翻译费用。"
    )
    (profile[2] / "learning/pairs/.translate_state.json").unlink()
    client = fake_client(monkeypatch, ['["Only the new record is translated."]'])
    assert run(profile, "--date", "2026-01-01", "--no-classify") == 0
    assert len(client.messages.calls) == 1
    assert "新到达" in client.messages.calls[0]["messages"][0]["content"]
    output = profile[2] / "learning/pairs/2026-01-01.md"
    assert "Existing translation." in output.read_text()
    assert validate_file(profile, "2026-01-01.md") == []


def test_failed_day_preserves_completed_day_without_repeat_calls(profile, monkeypatch):
    source(profile)
    source(
        profile,
        "2026-01-02_next.md",
        [
            (
                "2026-01-02 01:00:00Z",
                "这是第二天的中文提示，需要完整解释故障恢复如何保留已经完成的有效结果。",
            )
        ],
    )
    client = fake_client(monkeypatch, ['["First day done."]', "not-json"])
    args = [
        "--since",
        "2026-01-01",
        "--through-date",
        "2026-01-02",
        "--oldest-first",
        "--no-classify",
    ]
    assert run(profile, *args) == 1
    assert len(client.messages.calls) == 2
    output = profile[2] / "learning/pairs"
    assert (output / "2026-01-01.md").exists() and not (output / "2026-01-02.md").exists()
    before = (output / "2026-01-01.md").read_bytes()
    recovered = fake_client(monkeypatch, ['["Second day recovered."]'])
    assert run(profile, *args) == 0
    assert len(recovered.messages.calls) == 1
    assert (output / "2026-01-01.md").read_bytes() == before
    assert validate_file(profile, "2026-01-02.md") == []


def test_validation_detects_visible_chinese_changed_without_ledger_change(profile, monkeypatch):
    source(profile)
    fake_client(monkeypatch, ['["English result."]'])
    assert run(profile, "--date", "2026-01-01", "--no-classify") == 0
    output = profile[2] / "learning/pairs/2026-01-01.md"
    output.write_text(output.read_text().replace("这是一个用于验证", "这是被错误改动的验证"))
    assert any("Chinese does not match" in error for error in validate_file(profile, output.name))


@pytest.mark.parametrize("args", [["--dry-run"], ["--dry-run", "--cheatsheet-only"], ["--doctor"]])
def test_planning_and_doctor_never_call_model_or_create_output(profile, monkeypatch, args):
    source(profile)
    monkeypatch.setattr(translate, "make_client", lambda *a: pytest.fail("model client created"))
    assert run(profile, *args) == 0
    assert not (profile[2] / "learning").exists()


def test_dry_run_does_not_even_read_the_selected_credential(profile, monkeypatch):
    source(profile)
    monkeypatch.setattr(
        config, "credential_value", lambda *a: pytest.fail("dry run read credentials")
    )
    assert run(profile, "--dry-run") == 0


def test_missing_owner_credential_fails_and_optional_user_skips(profile, monkeypatch):
    source(profile)
    monkeypatch.delenv("SYNTHETIC_TRANSLATION_KEY")
    monkeypatch.setenv("ANTHROPIC_API_KEY", "unselected-key")
    assert run(profile, "--date", "2026-01-01") != 0
    profile[1]["api"]["required"] = False
    save(profile)
    assert run(profile, "--date", "2026-01-01") == 0
    assert not (profile[2] / "learning").exists()


def test_selected_json_credential_is_only_fallback_and_never_default_discovery(
    profile, monkeypatch
):
    credential = profile[0].parent / "selected.json"
    credential.write_text(json.dumps({"selected_key": "synthetic-file-key"}))
    profile[1]["api"]["credential"].update(file=str(credential), json_key="selected_key")
    save(profile)
    settings = config.load(profile[0])
    assert config.credential_value(settings) == "synthetic-selected-key"
    monkeypatch.delenv("SYNTHETIC_TRANSLATION_KEY")
    assert config.credential_value(settings) == "synthetic-file-key"
    credential.unlink()
    assert config.credential_value(settings) is None


def test_root_override_preserves_relative_source_layout(profile, tmp_path):
    original = profile[2]
    replacement = tmp_path / "selected-worktree"
    (replacement / "sources/prompts").mkdir(parents=True)
    profile[1]["source_directory"] = str(original / "sources/prompts")
    profile[1]["output_directory"] = str(original / "learning/pairs")
    save(profile)
    settings = config.load(profile[0], root=str(replacement))
    assert settings["source_directory"] == replacement / "sources/prompts"
    assert settings["state_file"] == replacement / "learning/pairs/.translate_state.json"


def test_home_variables_and_standalone_command(profile, monkeypatch):
    monkeypatch.setenv("HOME", str(profile[2].parent))
    profile[1]["repository_root"] = "$HOME/repository"
    profile[1]["api"]["required"] = False
    save(profile)
    script = Path(__file__).resolve().parents[1] / "scripts/translate"
    result = subprocess.run(
        [str(script), "--config", str(profile[0]), "--doctor"],
        env=dict(os.environ, PROMPT_TRANSLATION_PYTHON=sys.executable),
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    assert not (profile[2] / "learning").exists()


def test_source_symlink_cannot_upload_unselected_file(profile, monkeypatch, tmp_path):
    outside = tmp_path / "outside.md"
    outside.write_text("Private source outside the selection.")
    (profile[2] / "sources/prompts/2026-01-01_external.md").symlink_to(outside)
    monkeypatch.setattr(translate, "make_client", lambda *a: pytest.fail("model client created"))
    assert run(profile, "--date", "2026-01-01") == 1


def test_existing_output_symlink_is_not_read_or_overwritten(profile, monkeypatch, tmp_path):
    source(profile)
    outside = tmp_path / "protected.txt"
    outside.write_text("Protected contents.")
    output = profile[2] / "learning/pairs"
    output.mkdir(parents=True)
    (output / "2026-01-01.md").symlink_to(outside)
    monkeypatch.setattr(translate, "make_client", lambda *a: pytest.fail("model client created"))
    assert run(profile, "--date", "2026-01-01") == 1
    assert outside.read_text() == "Protected contents."


@pytest.mark.parametrize(
    "field,value",
    [
        ("source_directory", "../outside"),
        ("state_file", "sources/prompts/state.json"),
        ("generated_marker", "<!-- closed -->"),
    ],
)
def test_config_rejects_conflicting_paths_and_marker(profile, field, value):
    profile[1][field] = value
    save(profile)
    with pytest.raises(config.ConfigurationError):
        config.load(profile[0])


@pytest.mark.parametrize("value", ["[2]", "[true]", '["1"]'])
def test_classifier_rejects_nonbinary_values(value):
    client = SimpleNamespace(messages=FakeMessages([value]))
    with pytest.raises(RuntimeError, match="0 or 1"):
        translate.classify_substantive(client, ["synthetic prompt"], "synthetic-model")


def test_malformed_reply_diagnostics_do_not_echo_response_body():
    client = SimpleNamespace(messages=FakeMessages(["PRIVATE_REPLY_SENTINEL"]))
    with pytest.raises(RuntimeError) as error:
        translate.translate_batch(client, ["synthetic prompt"], "synthetic-model")
    assert "PRIVATE_REPLY_SENTINEL" not in str(error.value)


def test_cheatsheet_reads_daily_pairs_and_dates(profile, monkeypatch):
    source(profile)
    fake_client(monkeypatch, ['["English result."]'])
    assert run(profile, "--date", "2026-01-01", "--no-classify") == 0
    pairs, start, end = translate.load_existing_pairs(200)
    assert len(pairs) == 1 and start.date().isoformat() == "2026-01-01" and start == end
    client = fake_client(
        monkeypatch,
        [
            "# Chinese-English style cheatsheet\n\n| Chinese | English |\n|---|---|\n| 示例 | Example |"
        ],
    )
    assert run(profile, "--cheatsheet-only") == 0
    assert client.messages.calls[0]["system"][0]["text"] == profile[1]["prompts"]["cheatsheet"]
    assert (profile[2] / "learning/cheatsheet.md").exists()
