#!/usr/bin/env python3
"""Shared outcomes for direct tmux delivery and orchestrator wake attempts."""


class SendOutcome:
    CONTACTED = "CONTACTED"
    HELD_FOCUS = "HELD_FOCUS"
    ENTER_UNCONFIRMED = "ENTER_UNCONFIRMED"
    SENT_BUT_HELD = "SENT_BUT_HELD"
    DEAD_TARGET = "DEAD_TARGET"
    REFUSED_TARGET = "REFUSED_TARGET"
    REFUSED_STRAND = "REFUSED_STRAND"
    REFUSED_UNRECORDABLE = "REFUSED_UNRECORDABLE"
    REFUSED_PREPASTE = "REFUSED_PREPASTE"
    ALL = frozenset((
        CONTACTED, HELD_FOCUS, ENTER_UNCONFIRMED, SENT_BUT_HELD,
        DEAD_TARGET, REFUSED_TARGET, REFUSED_STRAND,
        REFUSED_UNRECORDABLE, REFUSED_PREPASTE))
