#!/usr/bin/env bash
set -euo pipefail

config_file="${BACKUP_CONFIG:-${HOME}/.config/backup/config}"
output_file="-"
temporary_file=""

usage() {
  printf 'usage: %s [--config FILE] [--output FILE|-]\n' "${0##*/}" >&2
}

fail() {
  printf 'launcher generation failed: %s\n' "$1" >&2
  exit 1
}

while (( $# > 0 )); do
  case "$1" in
    --config)
      (( $# >= 2 )) || { usage; exit 2; }
      config_file=$2
      shift 2
      ;;
    --output)
      (( $# >= 2 )) || { usage; exit 2; }
      output_file=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

[[ -f "${config_file}" ]] || fail "configuration file not found: ${config_file}"
# shellcheck disable=SC1090
source "${config_file}"

CLAUDE_PROFILES="${CLAUDE_PROFILES:-}"
CODEX_PROFILES="${CODEX_PROFILES:-}"
OPENCODE_PROFILES="${OPENCODE_PROFILES:-}"
DSH_PROFILES="${DSH_PROFILES:-}"

validate_entry() {
  local tool=$1 label=$2 path=$3
  [[ "${label}" =~ ^[a-z0-9][a-z0-9_-]*$ ]] || fail "${tool} label is unsafe: ${label}"
  [[ "${path}" == /* && "${path}" != / && "${path}" != "${HOME}" ]] ||
    fail "${tool} root must be an absolute non-home path for label ${label}"
  [[ "${path}" != *$'\n'* ]] || fail "${tool} root contains a newline for label ${label}"
}

emit_space_separated() {
  local tool=$1 command_name=$2 variable_name=$3
  local value entry label path seen=""
  value=${!variable_name}
  for entry in ${value}; do
    label=${entry%%:*}
    path=${entry#*:}
    [[ -n "${label}" && "${label}" != "${entry}" && -n "${path}" ]] ||
      fail "malformed ${variable_name} entry: ${entry}"
    validate_entry "${tool}" "${label}" "${path}"
    [[ " ${seen} " != *" ${label} "* ]] || fail "duplicate ${tool} label: ${label}"
    seen="${seen} ${label}"
    case "${tool}" in
      claude)
        printf '%s-%s() {\n  CLAUDE_CONFIG_DIR=%q command %s "$@"\n}\n\n' \
          "${command_name}" "${label}" "${path}" "${command_name}"
        ;;
      codex)
        printf '%s-%s() {\n  CODEX_HOME=%q command %s "$@"\n}\n\n' \
          "${command_name}" "${label}" "${path}" "${command_name}"
        ;;
      opencode)
        printf '%s-%s() {\n  local profile_root=%q\n  XDG_DATA_HOME="$profile_root/share" XDG_STATE_HOME="$profile_root/state" XDG_CONFIG_HOME="$profile_root/config" command %s "$@"\n}\n\n' \
          "${command_name}" "${label}" "${path}" "${command_name}"
        ;;
    esac
  done
}

emit_dsh() {
  local entry label path seen=""
  while IFS= read -r entry; do
    [[ -n "${entry}" ]] || continue
    label=${entry%%:*}
    path=${entry#*:}
    [[ -n "${label}" && "${label}" != "${entry}" && -n "${path}" ]] ||
      fail "malformed DSH_PROFILES entry: ${entry}"
    validate_entry dsh "${label}" "${path}"
    [[ " ${seen} " != *" ${label} "* ]] || fail "duplicate dsh label: ${label}"
    seen="${seen} ${label}"
    printf 'dsh-%s() {\n  DSH_HOME=%q command dsh "$@"\n}\n\n' "${label}" "${path}"
  done <<< "${DSH_PROFILES}"
}

render() {
  printf '%s\n' '# Generated by agent-harness-profiles. Edit the config, then regenerate.'
  printf '%s\n\n' '# Plain commands continue to select their native default roots.'
  emit_space_separated claude claude CLAUDE_PROFILES
  emit_space_separated codex codex CODEX_PROFILES
  emit_space_separated opencode opencode OPENCODE_PROFILES
  emit_dsh
}

if [[ "${output_file}" == - ]]; then
  render
else
  [[ "${output_file}" == /* && "${output_file}" != / ]] || fail 'output path must be absolute and non-root'
  [[ ! -L "${output_file}" ]] || fail "refusing to replace symlinked output: ${output_file}"
  if [[ -f "${output_file}" ]] &&
    ! head -n 1 -- "${output_file}" | grep -Fqx '# Generated by agent-harness-profiles. Edit the config, then regenerate.'; then
    fail "refusing unmanaged output: ${output_file}"
  fi
  install -d -m 0700 "$(dirname -- "${output_file}")"
  temporary_file=$(mktemp "${output_file}.tmp.XXXXXX")
  trap '[[ -z "${temporary_file}" ]] || rm -f -- "${temporary_file}"' EXIT
  render > "${temporary_file}"
  chmod 0600 "${temporary_file}"
  mv -f -- "${temporary_file}" "${output_file}"
  temporary_file=""
  printf 'Generated launchers: %s\n' "${output_file}"
fi
