"""Configuration for this translator; no credential or repository discovery."""

from __future__ import annotations

import json
import math
import os
import re
from pathlib import Path
from urllib.parse import urlsplit


class ConfigurationError(ValueError):
    """A configuration failure with a diagnostic safe to print."""


DEFAULT_PROMPTS = {
    "translate": "Translate the supplied Chinese prompts into idiomatic English. Preserve intent, register, code, paths, URLs and technical terms. Return only a flat JSON array of nonempty English strings in the same order, with exactly one translation per prompt.",
    "classify": "Select Chinese prompts useful for learning nuanced English expression. Return 1 for reasoning, plans, opinions or substantive requirements and 0 for terse commands, acknowledgments or simple lookups. Return only a flat JSON array of integers 0 or 1, exactly one per prompt in the supplied order.",
    "cheatsheet": "Derive recurring Chinese-English expression patterns only from the supplied translated pairs. Write a Markdown cheatsheet with sections and tables of Chinese patterns, idiomatic English alternatives and a brief sample context. Do not invent patterns absent from the sample. Start with '# Chinese-English style cheatsheet'.",
}
DEFAULT_MARKER = "<!-- Generated by prompt-translation/scripts/translate."
ZERO_PRICES = {
    name: {field: 0.0 for field in ("input", "output", "cache_write", "cache_read")}
    for name in ("sonnet", "opus", "haiku")
}


def default_config():
    return os.environ.get("PROMPT_TRANSLATION_CONFIG") or str(
        Path(os.environ.get("XDG_CONFIG_HOME") or Path.home() / ".config")
        / "prompt-translation/config.json"
    )


def resolve_path(value, base):
    if not isinstance(value, (str, Path)) or not str(value) or "\0" in str(value):
        raise ConfigurationError("configuration-path-invalid")
    expanded = os.path.expandvars(os.path.expanduser(str(value)))
    if re.search(r"\$(?:[A-Za-z_][A-Za-z_0-9]*|\{[^}]+\})", expanded):
        raise ConfigurationError("configuration-variable-unresolved")
    path = Path(expanded)
    return ((base / path) if not path.is_absolute() else path).resolve()


def load(path, root=None):
    path = resolve_path(path, Path.cwd())
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        raise ConfigurationError("configuration-unreadable") from None
    allowed = {
        "schema",
        "repository_root",
        "source_directory",
        "output_directory",
        "cheatsheet_path",
        "state_file",
        "models",
        "prompts",
        "filters",
        "pipeline_revision",
        "api",
        "pricing",
        "generated_marker",
    }
    if (
        not isinstance(value, dict)
        or value.get("schema") != "prompt-translation/v1"
        or set(value) - allowed
    ):
        raise ConfigurationError("configuration-schema-invalid")
    original = resolve_path(value.get("repository_root"), path.parent)
    repository = resolve_path(root, Path.cwd()) if root is not None else original
    if not repository.is_dir():
        raise ConfigurationError("repository-root-missing")
    value["repository_root"] = repository

    def repository_path(raw):
        configured = resolve_path(raw, original)
        if not configured.is_relative_to(original) or configured == original:
            raise ConfigurationError("configured-path-outside-repository")
        selected = resolve_path(configured.relative_to(original), repository)
        if not selected.is_relative_to(repository) or selected == repository:
            raise ConfigurationError("selected-path-outside-repository")
        return selected

    for name in ("source_directory", "output_directory", "cheatsheet_path"):
        value[name] = repository_path(value.get(name))
    if not value["source_directory"].is_dir():
        raise ConfigurationError("source-directory-missing")
    if value["output_directory"].is_relative_to(value["source_directory"]) or value[
        "source_directory"
    ].is_relative_to(value["output_directory"]):
        raise ConfigurationError("source-and-output-must-not-overlap")
    if "state_file" in value:
        raw = resolve_path(value["state_file"], original)
        value["state_file"] = (
            repository_path(value["state_file"]) if raw.is_relative_to(original) else raw
        )
    else:
        value["state_file"] = value["output_directory"] / ".translate_state.json"
    if value["state_file"] == value["cheatsheet_path"] or any(
        value[name].is_relative_to(value["source_directory"])
        for name in ("state_file", "cheatsheet_path")
    ):
        raise ConfigurationError("generated-path-conflict")
    models = value.get("models")
    if (
        not isinstance(models, dict)
        or set(models) != {"translate", "classify"}
        or any(
            not isinstance(model, str) or not model.strip() or "\n" in model
            for model in models.values()
        )
    ):
        raise ConfigurationError("models-must-be-explicit")
    prompts = value.setdefault("prompts", {})
    if not isinstance(prompts, dict) or set(prompts) - set(DEFAULT_PROMPTS):
        raise ConfigurationError("prompts-invalid")
    for name, default in DEFAULT_PROMPTS.items():
        prompts.setdefault(name, default)
        if not isinstance(prompts[name], str) or not prompts[name].strip():
            raise ConfigurationError("prompt-text-invalid")
    filters = value.setdefault("filters", {})
    if not isinstance(filters, dict) or set(filters) - {
        "min_chars",
        "max_chars",
        "min_chinese_ratio",
    }:
        raise ConfigurationError("filters-invalid")
    for key, default in (("min_chars", 30), ("max_chars", 2000)):
        filters.setdefault(key, default)
        if type(filters[key]) is not int or filters[key] < 1:
            raise ConfigurationError("filter-length-invalid")
    if filters["max_chars"] < filters["min_chars"]:
        raise ConfigurationError("filter-length-order-invalid")
    ratio = filters.setdefault("min_chinese_ratio", 0.1)
    if type(ratio) not in {int, float} or not math.isfinite(ratio) or not 0 <= ratio <= 1:
        raise ConfigurationError("filter-ratio-invalid")
    revision = value.setdefault("pipeline_revision", 2)
    if type(revision) is not int or revision < 1:
        raise ConfigurationError("pipeline-revision-invalid")
    marker = value.setdefault("generated_marker", DEFAULT_MARKER)
    if (
        not isinstance(marker, str)
        or not marker.startswith("<!-- ")
        or "-->" in marker
        or "\n" in marker
    ):
        raise ConfigurationError("generated-marker-must-be-comment-prefix")
    api = value.get("api")
    if not isinstance(api, dict) or set(api) - {
        "base_url",
        "credential",
        "required",
        "timeout",
        "max_retries",
    }:
        raise ConfigurationError("api-config-invalid")
    endpoint = api.get("base_url")
    if not isinstance(endpoint, str):
        raise ConfigurationError("api-url-required")
    parsed = urlsplit(endpoint)
    if (
        parsed.scheme not in {"https", "http"}
        or not parsed.hostname
        or parsed.username
        or parsed.password
        or parsed.query
        or parsed.fragment
    ):
        raise ConfigurationError("api-url-invalid")
    if parsed.scheme == "http" and parsed.hostname not in {"localhost", "127.0.0.1", "::1"}:
        raise ConfigurationError("api-url-requires-https")
    api.setdefault("required", True)
    api.setdefault("timeout", 600)
    api.setdefault("max_retries", 2)
    if (
        type(api["required"]) is not bool
        or type(api["timeout"]) not in {int, float}
        or not math.isfinite(api["timeout"])
        or api["timeout"] <= 0
        or type(api["max_retries"]) is not int
        or api["max_retries"] < 0
    ):
        raise ConfigurationError("api-options-invalid")
    credential = api.get("credential")
    if (
        not isinstance(credential, dict)
        or set(credential) - {"file", "json_key", "environment", "kind"}
        or not (credential.get("file") or credential.get("environment"))
    ):
        raise ConfigurationError("credential-selector-required")
    if "file" in credential:
        credential["file"] = resolve_path(credential["file"], path.parent)
    for key in ("json_key", "environment", "kind"):
        if key in credential and (not isinstance(credential[key], str) or not credential[key]):
            raise ConfigurationError("credential-selector-invalid")
    if credential.get("environment") and not re.fullmatch(
        r"[A-Za-z_][A-Za-z_0-9]*", credential["environment"]
    ):
        raise ConfigurationError("credential-environment-invalid")
    if "json_key" in credential and "file" not in credential:
        raise ConfigurationError("credential-json-key-needs-file")
    for generated in (value["state_file"], value["cheatsheet_path"]):
        if generated in {path, credential.get("file")}:
            raise ConfigurationError("generated-path-conflicts-with-configuration")
    prices = value.get("pricing")
    if prices is not None:
        if (
            not isinstance(prices, dict)
            or not prices
            or any(not isinstance(name, str) or not name for name in prices)
        ):
            raise ConfigurationError("pricing-invalid")
        for rates in prices.values():
            if (
                not isinstance(rates, dict)
                or set(rates) != {"input", "output", "cache_write", "cache_read"}
                or any(
                    type(rate) not in {int, float} or not math.isfinite(rate) or rate < 0
                    for rate in rates.values()
                )
            ):
                raise ConfigurationError("pricing-rate-invalid")
    return value


def credential_value(settings):
    selected = settings["api"]["credential"]
    key = os.environ.get(selected["environment"]) if selected.get("environment") else None
    if not key and selected.get("file"):
        try:
            text = selected["file"].read_text(encoding="utf-8")
            if selected.get("json_key"):
                data = json.loads(text)
                key = data.get(selected["json_key"]) if isinstance(data, dict) else None
            else:
                key = text.strip()
        except FileNotFoundError:
            key = None
        except (OSError, ValueError):
            raise ConfigurationError("configured-credential-unreadable") from None
    if key is not None and (
        not isinstance(key, str) or not key.strip() or any(c.isspace() for c in key)
    ):
        raise ConfigurationError("configured-credential-invalid")
    return key
